apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=quay.io/nadyita/testapp
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/myimage.allow-tags: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  name: testapp
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp
  source:
    path: app
    repoURL: https://github.com/Nadyita/testproject.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
